# Generated by Django 4.1.5 on 2023-01-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottoncandy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='book',
        ),
    ]
