# Generated by Django 4.1.5 on 2023-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('synopsis', models.TextField()),
                ('category', models.CharField(choices=[('horror', 'horror'), ('crime', 'crime'), ('not specified', 'not specified')], default='not specified', max_length=20)),
            ],
        ),
    ]
